# Generated by Django 3.0.6 on 2021-09-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_id', models.TextField(null=True)),
                ('source', models.TextField(null=True)),
                ('medium', models.TextField(null=True)),
                ('campaign', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('term', models.TextField(null=True)),
            ],
        ),
    ]
