# Generated by Django 3.0.6 on 2021-09-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Данные для входа',
                'verbose_name_plural': 'Данные для входа',
                'ordering': ['-id'],
            },
        ),
    ]
