# Generated by Django 3.0.6 on 2021-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('value', models.CharField(max_length=255, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Входные данные',
                'verbose_name_plural': 'Входные данные',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('reader', 'Чтение'), ('commenter', 'Комментирование'), ('writer', 'Редактирование'), ('owner', 'Владелец')], max_length=16)),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
    ]
