# Generated by Django 3.0.6 on 2021-09-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startpage', '0002_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Владелец копий',
                'verbose_name_plural': 'Владелец копий',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('google_drive_url', models.CharField(max_length=1024)),
                ('bitrix_smr', models.CharField(max_length=16, verbose_name='Подразделение СМР')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проектов',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('google_drive_url', models.CharField(max_length=1024)),
                ('project_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startpage.ProjectGroup')),
            ],
            options={
                'verbose_name': 'Шаблон папки проекта',
                'verbose_name_plural': 'Шаблоны папок проектов',
                'ordering': ['-id'],
            },
        ),
    ]
